import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

type Lang = "uz" | "ru" | "en";

const dict = {
  uz: {
    appTagline: "Distributsiya biznesini boshqarishning yagona platformasi",
    welcomeBack: "Xush kelibsiz",
    signInSubtitle: "Distr ish maydoniga kiring",
    email: "Elektron pochta",
    password: "Parol",
    signIn: "Kirish",
    demoNote: "Demo rejim — istalgan ma'lumotlar ishlaydi.",
    search: "Qidirish…",
    logout: "Chiqish",
    // nav
    dashboard: "Boshqaruv paneli",
    clients: "Mijozlar",
    sales: "Sotuvlar",
    staff: "Xodimlar",
    warehouse: "Ombor",
    finance: "Moliya",
    production: "Ishlab chiqarish",
    liveMap: "Jonli xarita",
    reports: "Hisobotlar",
    calendar: "Kalendar",
    notifications: "Bildirishnomalar",
    settings: "Sozlamalar",
    profile: "Profil",
    // dashboard
    overview: "Biznesingizning umumiy ko'rinishi.",
    totalSales: "Jami sotuvlar",
    activeClients: "Faol mijozlar",
    revenue: "Daromad",
    orders: "Buyurtmalar",
    salesPerformance: "Sotuv samaradorligi",
    ordersByMonth: "Oylik buyurtmalar",
    recentActivity: "So'nggi faollik",
    topClients: "Eng yaxshi mijozlar",
    topStaff: "Eng yaxshi xodimlar",
    salesByCategory: "Kategoriya bo'yicha",
    // common
    add: "Qo'shish",
    edit: "Tahrirlash",
    save: "Saqlash",
    cancel: "Bekor qilish",
    name: "Ism",
    phone: "Telefon",
    location: "Manzil",
    status: "Holat",
    joined: "Qo'shilgan",
    all: "Hammasi",
    active: "Faol",
    inactive: "Faol emas",
    pending: "Kutilmoqda",
    delivered: "Yetkazildi",
    cancelled: "Bekor qilindi",
    inProgress: "Jarayonda",
    completed: "Tugallandi",
    delayed: "Kechikkan",
    // pages
    clientsDesc: "Mijozlarni va ularning hisoblarini boshqaring.",
    addClient: "Mijoz qo'shish",
    editClient: "Mijozni tahrirlash",
    salesDesc: "Buyurtmalarni kuzating va oylik samaradorlikni ko'ring.",
    monthlySales: "Oylik sotuvlar",
    orderId: "Buyurtma ID",
    client: "Mijoz",
    date: "Sana",
    amount: "Summa",
    staffDesc: "Jamoa a'zolari, rollar va samaradorlik.",
    role: "Rol",
    performance: "Samaradorlik",
    warehouseDesc: "Ombor mahsulotlari va zaxirasi.",
    sku: "SKU",
    product: "Mahsulot",
    category: "Kategoriya",
    stock: "Zaxira",
    threshold: "Minimum",
    lowStock: "Kam zaxira",
    inStock: "Mavjud",
    financeDesc: "Daromad, xarajatlar va oylik xulosa.",
    income: "Daromad",
    expense: "Xarajat",
    netProfit: "Sof foyda",
    monthlySummary: "Oylik xulosa",
    transactions: "Tranzaksiyalar",
    type: "Turi",
    party: "Tomon",
    productionDesc: "Faol ishlab chiqarish partiyalari.",
    batch: "Partiya",
    quantity: "Miqdor",
    start: "Boshlanish",
    due: "Muddati",
    liveMapDesc: "Agentlarini real vaqtda kuzatish.",
    activeAgents: "Faol Hodimlar",
    reportsDesc: "Tahliliy hisobotlar va biznes ko'rsatkichlari.",
    calendarDesc: "Rejalashtirilgan tadbirlar va vazifalar.",
    notificationsDesc: "Tizim bildirishnomalari va ogohlantirishlar.",
    settingsDesc: "Ish maydoni sozlamalari.",
    profileDesc: "Sizning profil ma'lumotlaringiz.",
    language: "Til",
    theme: "Mavzu",
    light: "Yorug'",
    dark: "Qorong'i",
    notFound: "Hech narsa topilmadi.",
    today: "Bugun",
    growth: "o'sish",
    new: "yangi",
    markRead: "O'qilgan deb belgilash",
    upcoming: "Yaqinlashayotgan tadbirlar",
    noEvents: "Bu kun uchun tadbirlar yo'q.",
    calendarDailyNotes: "Kunlik eslatmalar",
    calendarActiveDays: "faol kun",
    calendarNotesCount: "eslatma",
    calendarTitle: "Sarlavha",
    calendarWriteNote: "Eslatmani yozing...",
    calendarClearDay: "Kunni tozalash",
    calendarNoNotesForDay: "Bu kun uchun hali eslatma yo'q.",
    calendarDeleteNote: "Eslatmani o'chirish",
    calendarNotesInMonth: "shu oyda eslatma",
    calendarUntitledNote: "Nomsiz eslatma",
    online: "Online",
    offline: "Offline",
    supervisor: "Supervisor",
    deliverer: "Yetkazuvchi",
    allRoles: "Hammasi",
    agents: "Agentlar",
    supervisors: "Supervisorlar",
    deliverers: "Yetkazuvchilar",
    speed: "Tezlik",
    workStartTime: "Ish boshlash vaqti",
    distanceTraveled: "Yurgan masofa",
    kmh: "km/soat",
    km: "km",
    agentInfo: "Agent ma'lumotlari",
    notAvailable: "Mavjud emas",
    clientsOnMap: "Xaritadagi mijozlar",
    showClients: "Mijozlarni ko'rsatish",
    hideClients: "Mijozlarni yashirish",
    lastSale: "So'nggi sotuv",
    debt: "Qarz",
    agent: "Agent",
    filial: "Filial",
    noClients: "Mijozlar topilmadi",
    errorTitle: "Ulanishda xatolik",
    errorClientsLoad:
      "Mijozlar ro'yxatini yuklash mumkin emas. Iltimos, keyinroq qayta urinib ko'ring.",
    comingSoon: "Tez kunda",
    dateBegin: "Boshlanish sanasi",
    dateEnd: "Tugash sanasi",
    branchId: "Filial ID",
    searchCategoryOrProduct: "Kategoriya yoki mahsulot qidirish",
    totalSalesAmount: "Jami savdo (summa)",
    totalVolumeKg: "Jami hajm (kg)",
    ordersClients: "Buyurtmalar / mijozlar",
    planCompletion: "Reja bajarilishi",
    amountByCategoryChart: "Kategoriyalar bo'yicha summa (grafik)",
    categoryShare: "Kategoriya ulushi",
    salesByCategories: "Kategoriyalar bo'yicha savdo",
    qty: "Miqdor",
    qtyPercent: "Miqdor %",
    amountPercent: "Summa %",
    topProducts: "Top mahsulotlar",
    agentMetrics: "Agentlar bo'yicha ko'rsatkichlar",
    result: "Natija",
    planFact: "Reja / Fakt",
    orderClient: "Buyurtma / Mijoz",
    totalAmount: "Jami summa",
    ordersLower: "buyurtma",
    sortDateNewOld: "Sana: yangi-eski",
    sortDateOldNew: "Sana: eski-yangi",
    sortAmountHighLow: "Summa: katta-kichik",
    sortAmountLowHigh: "Summa: kichik-katta",
    sortQtyHighLow: "Miqdor: katta-kichik",
    sortQtyLowHigh: "Miqdor: kichik-katta",
    sortClientAZ: "Mijoz: A-Z",
    sortClientZA: "Mijoz: Z-A",
    cardsView: "Kartalar",
    tableView: "Jadval",
    totalProductsCount: "Umumiy mahsulotlar soni",
    totalVolumeQty: "Jami hajm (miqdor)",
    dailyIncomeExpenseTrend: "Kunlik daromad / xarajat dinamikasi",
    statusShare: "Statuslar ulushi",
    id: "ID",
    products: "Mahsulotlar",
    navMain: "Asosiy",
    navOperations: "Operatsiyalar",
    navInsights: "Tahlillar",
    navAccount: "Hisob",
    expandSidebar: "Yon panelni kengaytirish",
    collapseSidebar: "Yon panelni yig'ish",
    user: "Foydalanuvchi",
    notificationTitle1: "Yangi buyurtma #ORD-3411",
    notificationDesc1: "Mega Retail LLC buyurtma joylashtirdi — $14,200",
    notificationTime1: "5 daq",
    notificationTitle2: "Kam zaxira ogohlantirishi",
    notificationDesc2: "Coffee 250g minimumdan past (38 qoldi)",
    notificationTime2: "1 soat",
    notificationTitle3: "Partiya tugallandi",
    notificationDesc3: "PRD-558 — Detergent 3kg (2,400 dona)",
    notificationTime3: "3 soat",
    notificationTitle4: "Yangi mijoz qo'shildi",
    notificationDesc4: "Tashkent Foods mijozlar ro'yxatiga qo'shildi",
    notificationTime4: "5 soat",
    notificationTitle5: "Eslatma",
    notificationDesc5: "Oylik hisobot topshirish muddati ertaga",
    notificationTime5: "1 kun",
    notificationTitle6: "Buyurtma yetkazildi",
    notificationDesc6: "#ORD-3407 — Khiva Wholesale",
    notificationTime6: "2 kun",
    sortAZ: "A-Z",
    sortZA: "Z-A",
    sortDebtHighLow: "Qarz: katta-kichik",
    sortDebtLowHigh: "Qarz: kichik-katta",
    sortLastSaleNewOld: "So'nggi savdo: yangi-eski",
    sortLastSaleOldNew: "So'nggi savdo: eski-yangi",
    sortNameAZ: "Nomi: A-Z",
    sortNameZA: "Nomi: Z-A",
    sortStockHighLow: "Qoldiq: katta-kichik",
    sortStockLowHigh: "Qoldiq: kichik-katta",
    sortPriceHighLow: "Narx: katta-kichik",
    sortPriceLowHigh: "Narx: kichik-katta",
    contact: "Aloqa",
    username: "Foydalanuvchi nomi",
    company: "Kompaniya",
    manager: "Menejer",
    oneCData: "1C ma'lumotlari",
    oneCId: "1C ID",
    oneCLogin: "1C login",
    topAgents: "Top agentlar",
    topGroups: "Top guruhlar",
    totalQty: "Jami miqdor",
    photo: "Foto",
    returned: "Qaytgan",
    clientOpenProfile: "Mijoz · Profilni ochish",
    visit: "Tashrif",
    comment: "Izoh",
    back: "Orqaga",
    clientProfile: "Mijoz profili",
    loading: "Yuklanmoqda...",
    photoReports: "Foto hisobotlar",
    rejectedPhotos: "Rad etilgan rasmlar",
    payments: "To'lovlar",
    locationLandmark: "Manzil orientir",
    activities: "Faoliyatlar",
    noData: "Ma'lumot yo'q",
    photoReport: "Foto hisobot",
    viewFull: "To'liq ko'rish",
    reasonNotSpecified: "Sabab ko'rsatilmagan",
    noComment: "Izoh yo'q",
    payment: "To'lov",
    cash: "Naqd",
    card: "Karta",
  },
  ru: {
    appTagline: "Единая платформа для управления дистрибьюторским бизнесом",
    welcomeBack: "С возвращением",
    signInSubtitle: "Войдите в рабочее пространство Distr",
    email: "Эл. почта",
    password: "Пароль",
    signIn: "Войти",
    demoNote: "Демо-режим — подойдут любые данные.",
    search: "Поиск…",
    logout: "Выйти",
    dashboard: "Панель",
    clients: "Клиенты",
    sales: "Продажи",
    staff: "Сотрудники",
    warehouse: "Склад",
    finance: "Финансы",
    production: "Производство",
    liveMap: "Карта",
    reports: "Отчёты",
    calendar: "Календарь",
    notifications: "Уведомления",
    settings: "Настройки",
    profile: "Профиль",
    overview: "Обзор вашего бизнеса.",
    totalSales: "Всего продаж",
    activeClients: "Активные клиенты",
    revenue: "Выручка",
    orders: "Заказы",
    salesPerformance: "Динамика продаж",
    ordersByMonth: "Заказы по месяцам",
    recentActivity: "Недавние события",
    topClients: "Топ клиенты",
    topStaff: "Топ сотрудники",
    salesByCategory: "По категориям",
    add: "Добавить",
    edit: "Изменить",
    save: "Сохранить",
    cancel: "Отмена",
    name: "Имя",
    phone: "Телефон",
    location: "Локация",
    status: "Статус",
    joined: "Добавлен",
    all: "Все",
    active: "Активен",
    inactive: "Неактивен",
    pending: "В ожидании",
    delivered: "Доставлено",
    cancelled: "Отменено",
    inProgress: "В процессе",
    completed: "Завершено",
    delayed: "Задержано",
    clientsDesc: "Управляйте клиентами и их аккаунтами.",
    addClient: "Добавить клиента",
    editClient: "Редактировать клиента",
    salesDesc: "Отслеживайте заказы и динамику продаж.",
    monthlySales: "Продажи по месяцам",
    orderId: "ID заказа",
    client: "Клиент",
    date: "Дата",
    amount: "Сумма",
    staffDesc: "Сотрудники, роли и эффективность.",
    role: "Роль",
    performance: "Эффективность",
    warehouseDesc: "Складские товары и остатки.",
    sku: "Артикул",
    product: "Товар",
    category: "Категория",
    stock: "Остаток",
    threshold: "Минимум",
    lowStock: "Мало остатка",
    inStock: "В наличии",
    financeDesc: "Доходы, расходы и месячная сводка.",
    income: "Доход",
    expense: "Расход",
    netProfit: "Чистая прибыль",
    monthlySummary: "Сводка за месяц",
    transactions: "Транзакции",
    type: "Тип",
    party: "Контрагент",
    productionDesc: "Активные производственные партии.",
    batch: "Партия",
    quantity: "Кол-во",
    start: "Начало",
    due: "Срок",
    liveMapDesc: "Отслеживание агентов в реальном времени.",
    activeAgents: "Активные агенты",
    reportsDesc: "Аналитические отчёты и показатели.",
    calendarDesc: "Запланированные события и задачи.",
    notificationsDesc: "Системные уведомления и оповещения.",
    settingsDesc: "Настройки рабочего пространства.",
    profileDesc: "Информация вашего профиля.",
    language: "Язык",
    theme: "Тема",
    light: "Светлая",
    dark: "Тёмная",
    notFound: "Ничего не найдено.",
    today: "Сегодня",
    growth: "рост",
    new: "новых",
    markRead: "Отметить прочитанным",
    upcoming: "Предстоящие события",
    noEvents: "На этот день событий нет.",
    calendarDailyNotes: "Ежедневные заметки",
    calendarActiveDays: "активных дней",
    calendarNotesCount: "заметок",
    calendarTitle: "Заголовок",
    calendarWriteNote: "Введите заметку...",
    calendarClearDay: "Очистить день",
    calendarNoNotesForDay: "На этот день пока нет заметок.",
    calendarDeleteNote: "Удалить заметку",
    calendarNotesInMonth: "заметок в этом месяце",
    calendarUntitledNote: "Заметка без названия",
    online: "Онлайн",
    offline: "Офлайн",
    supervisor: "Супервайзер",
    deliverer: "Доставщик",
    allRoles: "Все",
    agents: "Агенты",
    supervisors: "Супервайзеры",
    deliverers: "Доставщики",
    speed: "Скорость",
    workStartTime: "Начало работы",
    distanceTraveled: "Пройдено",
    kmh: "км/ч",
    km: "км",
    agentInfo: "Информация агента",
    notAvailable: "Недоступно",
    clientsOnMap: "Клиенты на карте",
    showClients: "Показать клиентов",
    hideClients: "Скрыть клиентов",
    lastSale: "Последняя продажа",
    debt: "Долг",
    agent: "Агент",
    filial: "Филиал",
    noClients: "Клиенты не найдены",
    errorTitle: "Ошибка подключения",
    errorClientsLoad: "Не удалось загрузить список клиентов. Пожалуйста, попробуйте позже.",
    comingSoon: "Скоро",
    dateBegin: "Дата начала",
    dateEnd: "Дата окончания",
    branchId: "ID филиала",
    searchCategoryOrProduct: "Поиск категории или товара",
    totalSalesAmount: "Общие продажи (сумма)",
    totalVolumeKg: "Общий объем (кг)",
    ordersClients: "Заказы / клиенты",
    planCompletion: "Выполнение плана",
    amountByCategoryChart: "Сумма по категориям (график)",
    categoryShare: "Доля категорий",
    salesByCategories: "Продажи по категориям",
    qty: "Кол-во",
    qtyPercent: "Кол-во %",
    amountPercent: "Сумма %",
    topProducts: "Топ товары",
    agentMetrics: "Показатели по агентам",
    result: "Результат",
    planFact: "План / Факт",
    orderClient: "Заказ / Клиент",
    totalAmount: "Общая сумма",
    ordersLower: "заказов",
    sortDateNewOld: "Дата: новые-старые",
    sortDateOldNew: "Дата: старые-новые",
    sortAmountHighLow: "Сумма: больше-меньше",
    sortAmountLowHigh: "Сумма: меньше-больше",
    sortQtyHighLow: "Кол-во: больше-меньше",
    sortQtyLowHigh: "Кол-во: меньше-больше",
    sortClientAZ: "Клиент: A-Z",
    sortClientZA: "Клиент: Z-A",
    cardsView: "Карточки",
    tableView: "Таблица",
    totalProductsCount: "Общее количество товаров",
    totalVolumeQty: "Общий объем (кол-во)",
    dailyIncomeExpenseTrend: "Динамика доходов/расходов по дням",
    statusShare: "Доля статусов",
    id: "ID",
    products: "Товары",
    navMain: "Главное",
    navOperations: "Операции",
    navInsights: "Аналитика",
    navAccount: "Аккаунт",
    expandSidebar: "Развернуть боковую панель",
    collapseSidebar: "Свернуть боковую панель",
    user: "Пользователь",
    notificationTitle1: "Новый заказ #ORD-3411",
    notificationDesc1: "Mega Retail LLC разместил заказ — $14,200",
    notificationTime1: "5 мин",
    notificationTitle2: "Предупреждение о низком остатке",
    notificationDesc2: "Coffee 250g ниже порога (осталось 38)",
    notificationTime2: "1 ч",
    notificationTitle3: "Партия завершена",
    notificationDesc3: "PRD-558 — Detergent 3kg (2,400 ед.)",
    notificationTime3: "3 ч",
    notificationTitle4: "Добавлен новый клиент",
    notificationDesc4: "Tashkent Foods добавлен в список клиентов",
    notificationTime4: "5 ч",
    notificationTitle5: "Напоминание",
    notificationDesc5: "Срок месячного отчета завтра",
    notificationTime5: "1 д",
    notificationTitle6: "Заказ доставлен",
    notificationDesc6: "#ORD-3407 — Khiva Wholesale",
    notificationTime6: "2 д",
    sortAZ: "A-Z",
    sortZA: "Z-A",
    sortDebtHighLow: "Долг: больше-меньше",
    sortDebtLowHigh: "Долг: меньше-больше",
    sortLastSaleNewOld: "Последняя продажа: новые-старые",
    sortLastSaleOldNew: "Последняя продажа: старые-новые",
    sortNameAZ: "Название: A-Z",
    sortNameZA: "Название: Z-A",
    sortStockHighLow: "Остаток: больше-меньше",
    sortStockLowHigh: "Остаток: меньше-больше",
    sortPriceHighLow: "Цена: больше-меньше",
    sortPriceLowHigh: "Цена: меньше-больше",
    contact: "Контакт",
    username: "Имя пользователя",
    company: "Компания",
    manager: "Менеджер",
    oneCData: "Данные 1C",
    oneCId: "1C ID",
    oneCLogin: "1C логин",
    topAgents: "Топ агенты",
    topGroups: "Топ группы",
    totalQty: "Общее кол-во",
    photo: "Фото",
    returned: "Возвраты",
    clientOpenProfile: "Клиент · Открыть профиль",
    visit: "Визит",
    comment: "Комментарий",
    back: "Назад",
    clientProfile: "Профиль клиента",
    loading: "Загрузка...",
    photoReports: "Фотоотчеты",
    rejectedPhotos: "Отклоненные фото",
    payments: "Платежи",
    locationLandmark: "Ориентир адреса",
    activities: "Активности",
    noData: "Нет данных",
    photoReport: "Фотоотчет",
    viewFull: "Открыть полностью",
    reasonNotSpecified: "Причина не указана",
    noComment: "Нет комментария",
    payment: "Платеж",
    cash: "Наличные",
    card: "Карта",
  },
  en: {
    appTagline: "One platform to run your entire distribution business",
    welcomeBack: "Welcome back",
    signInSubtitle: "Sign in to your Distr workspace",
    email: "Email",
    password: "Password",
    signIn: "Sign in",
    demoNote: "Demo mode — any credentials work.",
    search: "Search…",
    logout: "Logout",
    dashboard: "Dashboard",
    clients: "Clients",
    sales: "Sales",
    staff: "Staff",
    warehouse: "Warehouse",
    finance: "Finance",
    production: "Production",
    liveMap: "Live Map",
    reports: "Reports",
    calendar: "Calendar",
    notifications: "Notifications",
    settings: "Settings",
    profile: "Profile",
    overview: "Overview of your business.",
    totalSales: "Total Sales",
    activeClients: "Active Clients",
    revenue: "Revenue",
    orders: "Orders",
    salesPerformance: "Sales performance",
    ordersByMonth: "Orders by month",
    recentActivity: "Recent activity",
    topClients: "Top clients",
    topStaff: "Top staff",
    salesByCategory: "By category",
    add: "Add",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    name: "Name",
    phone: "Phone",
    location: "Location",
    status: "Status",
    joined: "Joined",
    all: "All",
    active: "Active",
    inactive: "Inactive",
    pending: "Pending",
    delivered: "Delivered",
    cancelled: "Cancelled",
    inProgress: "In progress",
    completed: "Completed",
    delayed: "Delayed",
    clientsDesc: "Manage your customers and accounts.",
    addClient: "Add client",
    editClient: "Edit client",
    salesDesc: "Track orders and monthly performance.",
    monthlySales: "Monthly sales",
    orderId: "Order ID",
    client: "Client",
    date: "Date",
    amount: "Amount",
    staffDesc: "Team members, roles and performance.",
    role: "Role",
    performance: "Performance",
    warehouseDesc: "Warehouse products and inventory.",
    sku: "SKU",
    product: "Product",
    category: "Category",
    stock: "Stock",
    threshold: "Threshold",
    lowStock: "Low stock",
    inStock: "In stock",
    financeDesc: "Income, expenses and monthly summary.",
    income: "Income",
    expense: "Expense",
    netProfit: "Net profit",
    monthlySummary: "Monthly summary",
    transactions: "Transactions",
    type: "Type",
    party: "Party",
    productionDesc: "Active production batches.",
    batch: "Batch",
    quantity: "Quantity",
    start: "Start",
    due: "Due",
    liveMapDesc: "Real-time tracking of field agents.",
    activeAgents: "Active agents",
    reportsDesc: "Analytics reports and KPIs.",
    calendarDesc: "Scheduled events and tasks.",
    notificationsDesc: "System notifications and alerts.",
    settingsDesc: "Workspace settings.",
    profileDesc: "Your profile information.",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    notFound: "No results found.",
    today: "Today",
    growth: "growth",
    new: "new",
    markRead: "Mark as read",
    upcoming: "Upcoming events",
    noEvents: "No events for this day.",
    calendarDailyNotes: "Daily notes",
    calendarActiveDays: "active days",
    calendarNotesCount: "notes",
    calendarTitle: "Title",
    calendarWriteNote: "Write your note...",
    calendarClearDay: "Clear day",
    calendarNoNotesForDay: "No notes for this day yet.",
    calendarDeleteNote: "Delete note",
    calendarNotesInMonth: "notes in this month",
    calendarUntitledNote: "Untitled note",
    online: "Online",
    offline: "Offline",
    supervisor: "Supervisor",
    deliverer: "Deliverer",
    allRoles: "All",
    agents: "Agents",
    supervisors: "Supervisors",
    deliverers: "Deliverers",
    speed: "Speed",
    workStartTime: "Work start time",
    distanceTraveled: "Distance traveled",
    kmh: "km/h",
    km: "km",
    agentInfo: "Agent info",
    notAvailable: "Not available",
    clientsOnMap: "Clients on map",
    showClients: "Show clients",
    hideClients: "Hide clients",
    lastSale: "Last sale",
    debt: "Debt",
    agent: "Agent",
    filial: "Branch",
    noClients: "No clients found",
    errorTitle: "Connection error",
    errorClientsLoad: "Failed to load clients list. Please try again later.",
    comingSoon: "Coming soon",
    dateBegin: "Start date",
    dateEnd: "End date",
    branchId: "Branch ID",
    searchCategoryOrProduct: "Search category or product",
    totalSalesAmount: "Total sales (amount)",
    totalVolumeKg: "Total volume (kg)",
    ordersClients: "Orders / clients",
    planCompletion: "Plan completion",
    amountByCategoryChart: "Amount by category (chart)",
    categoryShare: "Category share",
    salesByCategories: "Sales by categories",
    qty: "Qty",
    qtyPercent: "Qty %",
    amountPercent: "Amount %",
    topProducts: "Top products",
    agentMetrics: "Metrics by agents",
    result: "Result",
    planFact: "Plan / Fact",
    orderClient: "Order / Client",
    totalAmount: "Total amount",
    ordersLower: "orders",
    sortDateNewOld: "Date: new-old",
    sortDateOldNew: "Date: old-new",
    sortAmountHighLow: "Amount: high-low",
    sortAmountLowHigh: "Amount: low-high",
    sortQtyHighLow: "Qty: high-low",
    sortQtyLowHigh: "Qty: low-high",
    sortClientAZ: "Client: A-Z",
    sortClientZA: "Client: Z-A",
    cardsView: "Cards",
    tableView: "Table",
    totalProductsCount: "Total products count",
    totalVolumeQty: "Total volume (qty)",
    dailyIncomeExpenseTrend: "Daily income / expense trend",
    statusShare: "Status share",
    id: "ID",
    products: "Products",
    navMain: "Main",
    navOperations: "Operations",
    navInsights: "Insights",
    navAccount: "Account",
    expandSidebar: "Expand sidebar",
    collapseSidebar: "Collapse sidebar",
    user: "User",
    notificationTitle1: "New order #ORD-3411",
    notificationDesc1: "Mega Retail LLC placed an order — $14,200",
    notificationTime1: "5m",
    notificationTitle2: "Low stock alert",
    notificationDesc2: "Coffee 250g below threshold (38 left)",
    notificationTime2: "1h",
    notificationTitle3: "Batch completed",
    notificationDesc3: "PRD-558 — Detergent 3kg (2,400 units)",
    notificationTime3: "3h",
    notificationTitle4: "New client added",
    notificationDesc4: "Tashkent Foods joined your client list",
    notificationTime4: "5h",
    notificationTitle5: "Reminder",
    notificationDesc5: "Monthly report deadline tomorrow",
    notificationTime5: "1d",
    notificationTitle6: "Order delivered",
    notificationDesc6: "#ORD-3407 — Khiva Wholesale",
    notificationTime6: "2d",
    sortAZ: "A-Z",
    sortZA: "Z-A",
    sortDebtHighLow: "Debt: high-low",
    sortDebtLowHigh: "Debt: low-high",
    sortLastSaleNewOld: "Last sale: new-old",
    sortLastSaleOldNew: "Last sale: old-new",
    sortNameAZ: "Name: A-Z",
    sortNameZA: "Name: Z-A",
    sortStockHighLow: "Stock: high-low",
    sortStockLowHigh: "Stock: low-high",
    sortPriceHighLow: "Price: high-low",
    sortPriceLowHigh: "Price: low-high",
    contact: "Contact",
    username: "Username",
    company: "Company",
    manager: "Manager",
    oneCData: "1C data",
    oneCId: "1C ID",
    oneCLogin: "1C login",
    topAgents: "Top agents",
    topGroups: "Top groups",
    totalQty: "Total quantity",
    photo: "Photo",
    returned: "Returned",
    clientOpenProfile: "Client · Open profile",
    visit: "Visit",
    comment: "Comment",
    back: "Back",
    clientProfile: "Client profile",
    loading: "Loading...",
    photoReports: "Photo reports",
    rejectedPhotos: "Rejected photos",
    payments: "Payments",
    locationLandmark: "Address landmark",
    activities: "Activities",
    noData: "No data",
    photoReport: "Photo report",
    viewFull: "View full",
    reasonNotSpecified: "Reason not specified",
    noComment: "No comment",
    payment: "Payment",
    cash: "Cash",
    card: "Card",
  },
} as const;

type Key = string;

type Ctx = {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (k: Key) => string;
  theme: "light" | "dark";
  setTheme: (t: "light" | "dark") => void;
};

const C = createContext<Ctx | null>(null);

export function AppSettingsProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("uz");
  const [theme, setThemeState] = useState<"light" | "dark">("light");

  useEffect(() => {
    if (typeof window === "undefined") return;
    const l = (localStorage.getItem("distr.lang") as Lang) || "uz";
    const th = (localStorage.getItem("distr.theme") as "light" | "dark") || "light";
    setLangState(l);
    setThemeState(th);
  }, []);

  useEffect(() => {
    if (typeof document === "undefined") return;
    document.documentElement.classList.toggle("dark", theme === "dark");
  }, [theme]);

  const setLang = (l: Lang) => {
    localStorage.setItem("distr.lang", l);
    setLangState(l);
  };
  const setTheme = (t: "light" | "dark") => {
    localStorage.setItem("distr.theme", t);
    setThemeState(t);
  };

  const t = (k: Key) =>
    (dict[lang] as Record<string, string>)[k] ?? (dict.en as Record<string, string>)[k] ?? k;

  return <C.Provider value={{ lang, setLang, t, theme, setTheme }}>{children}</C.Provider>;
}

export function useSettings() {
  const ctx = useContext(C);
  if (!ctx) throw new Error("useSettings must be used within AppSettingsProvider");
  return ctx;
}

export const LANGS: { code: Lang; label: string; flag: string }[] = [
  { code: "uz", label: "O'zbekcha", flag: "🇺🇿" },
  { code: "ru", label: "Русский", flag: "🇷🇺" },
  { code: "en", label: "English", flag: "🇬🇧" },
];
