import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

type Lang = "uz" | "ru" | "en";

const dict = {
  uz: {
    appTagline: "Distributsiya biznesini boshqarishning yagona platformasi",
    welcomeBack: "Xush kelibsiz",
    signInSubtitle: "Distr ish maydoniga kiring",
    email: "Elektron pochta",
    password: "Parol",
    signIn: "Kirish",
    demoNote: "Demo rejim — istalgan ma'lumotlar ishlaydi.",
    search: "Qidirish…",
    logout: "Chiqish",
    // nav
    dashboard: "Boshqaruv paneli",
    clients: "Mijozlar",
    sales: "Sotuvlar",
    staff: "Xodimlar",
    warehouse: "Ombor",
    finance: "Moliya",
    production: "Ishlab chiqarish",
    liveMap: "Jonli xarita",
    reports: "Hisobotlar",
    calendar: "Kalendar",
    notifications: "Bildirishnomalar",
    settings: "Sozlamalar",
    profile: "Profil",
    // dashboard
    overview: "Biznesingizning umumiy ko'rinishi.",
    totalSales: "Jami sotuvlar",
    activeClients: "Faol mijozlar",
    revenue: "Daromad",
    orders: "Buyurtmalar",
    salesPerformance: "Sotuv samaradorligi",
    ordersByMonth: "Oylik buyurtmalar",
    recentActivity: "So'nggi faollik",
    topClients: "Eng yaxshi mijozlar",
    topStaff: "Eng yaxshi xodimlar",
    salesByCategory: "Kategoriya bo'yicha",
    // common
    add: "Qo'shish",
    edit: "Tahrirlash",
    save: "Saqlash",
    cancel: "Bekor qilish",
    name: "Ism",
    phone: "Telefon",
    location: "Manzil",
    status: "Holat",
    joined: "Qo'shilgan",
    all: "Hammasi",
    active: "Faol",
    inactive: "Faol emas",
    pending: "Kutilmoqda",
    delivered: "Yetkazildi",
    cancelled: "Bekor qilindi",
    inProgress: "Jarayonda",
    completed: "Tugallandi",
    delayed: "Kechikkan",
    // pages
    clientsDesc: "Mijozlarni va ularning hisoblarini boshqaring.",
    addClient: "Mijoz qo'shish",
    editClient: "Mijozni tahrirlash",
    salesDesc: "Buyurtmalarni kuzating va oylik samaradorlikni ko'ring.",
    monthlySales: "Oylik sotuvlar",
    orderId: "Buyurtma ID",
    client: "Mijoz",
    date: "Sana",
    amount: "Summa",
    staffDesc: "Jamoa a'zolari, rollar va samaradorlik.",
    role: "Rol",
    performance: "Samaradorlik",
    warehouseDesc: "Ombor mahsulotlari va zaxirasi.",
    sku: "SKU",
    product: "Mahsulot",
    category: "Kategoriya",
    stock: "Zaxira",
    threshold: "Minimum",
    lowStock: "Kam zaxira",
    inStock: "Mavjud",
    financeDesc: "Daromad, xarajatlar va oylik xulosa.",
    income: "Daromad",
    expense: "Xarajat",
    netProfit: "Sof foyda",
    monthlySummary: "Oylik xulosa",
    transactions: "Tranzaksiyalar",
    type: "Turi",
    party: "Tomon",
    productionDesc: "Faol ishlab chiqarish partiyalari.",
    batch: "Partiya",
    quantity: "Miqdor",
    start: "Boshlanish",
    due: "Muddati",
    liveMapDesc: "Agentlarini real vaqtda kuzatish.",
    activeAgents: "Faol Hodimlar",
    reportsDesc: "Tahliliy hisobotlar va biznes ko'rsatkichlari.",
    calendarDesc: "Rejalashtirilgan tadbirlar va vazifalar.",
    notificationsDesc: "Tizim bildirishnomalari va ogohlantirishlar.",
    settingsDesc: "Ish maydoni sozlamalari.",
    profileDesc: "Sizning profil ma'lumotlaringiz.",
    language: "Til",
    theme: "Mavzu",
    light: "Yorug'",
    dark: "Qorong'i",
    notFound: "Hech narsa topilmadi.",
    today: "Bugun",
    growth: "o'sish",
    new: "yangi",
    markRead: "O'qilgan deb belgilash",
    upcoming: "Yaqinlashayotgan tadbirlar",
    noEvents: "Bu kun uchun tadbirlar yo'q.",
    online: "Online",
    offline: "Offline",
    supervisor: "Supervisor",
    deliverer: "Yetkazuvchi",
    allRoles: "Hammasi",
    agents: "Agentlar",
    supervisors: "Supervisorlar",
    deliverers: "Yetkazuvchilar",
    speed: "Tezlik",
    workStartTime: "Ish boshlash vaqti",
    distanceTraveled: "Yurgan masofa",
    kmh: "km/soat",
    km: "km",
    agentInfo: "Agent ma'lumotlari",
    notAvailable: "Mavjud emas",
    clientsOnMap: "Xaritadagi mijozlar",
    showClients: "Mijozlarni ko'rsatish",
    hideClients: "Mijozlarni yashirish",
    lastSale: "So'nggi sotuv",
    debt: "Qarz",
    agent: "Agent",
    filial: "Filial",
    noClients: "Mijozlar topilmadi",
    errorTitle: "Ulanishda xatolik",
    errorClientsLoad:
      "Mijozlar ro'yxatini yuklash mumkin emas. Iltimos, keyinroq qayta urinib ko'ring.",
  },
  ru: {
    appTagline: "Единая платформа для управления дистрибьюторским бизнесом",
    welcomeBack: "С возвращением",
    signInSubtitle: "Войдите в рабочее пространство Distr",
    email: "Эл. почта",
    password: "Пароль",
    signIn: "Войти",
    demoNote: "Демо-режим — подойдут любые данные.",
    search: "Поиск…",
    logout: "Выйти",
    dashboard: "Панель",
    clients: "Клиенты",
    sales: "Продажи",
    staff: "Сотрудники",
    warehouse: "Склад",
    finance: "Финансы",
    production: "Производство",
    liveMap: "Карта",
    reports: "Отчёты",
    calendar: "Календарь",
    notifications: "Уведомления",
    settings: "Настройки",
    profile: "Профиль",
    overview: "Обзор вашего бизнеса.",
    totalSales: "Всего продаж",
    activeClients: "Активные клиенты",
    revenue: "Выручка",
    orders: "Заказы",
    salesPerformance: "Динамика продаж",
    ordersByMonth: "Заказы по месяцам",
    recentActivity: "Недавние события",
    topClients: "Топ клиенты",
    topStaff: "Топ сотрудники",
    salesByCategory: "По категориям",
    add: "Добавить",
    edit: "Изменить",
    save: "Сохранить",
    cancel: "Отмена",
    name: "Имя",
    phone: "Телефон",
    location: "Локация",
    status: "Статус",
    joined: "Добавлен",
    all: "Все",
    active: "Активен",
    inactive: "Неактивен",
    pending: "В ожидании",
    delivered: "Доставлено",
    cancelled: "Отменено",
    inProgress: "В процессе",
    completed: "Завершено",
    delayed: "Задержано",
    clientsDesc: "Управляйте клиентами и их аккаунтами.",
    addClient: "Добавить клиента",
    editClient: "Редактировать клиента",
    salesDesc: "Отслеживайте заказы и динамику продаж.",
    monthlySales: "Продажи по месяцам",
    orderId: "ID заказа",
    client: "Клиент",
    date: "Дата",
    amount: "Сумма",
    staffDesc: "Сотрудники, роли и эффективность.",
    role: "Роль",
    performance: "Эффективность",
    warehouseDesc: "Складские товары и остатки.",
    sku: "Артикул",
    product: "Товар",
    category: "Категория",
    stock: "Остаток",
    threshold: "Минимум",
    lowStock: "Мало остатка",
    inStock: "В наличии",
    financeDesc: "Доходы, расходы и месячная сводка.",
    income: "Доход",
    expense: "Расход",
    netProfit: "Чистая прибыль",
    monthlySummary: "Сводка за месяц",
    transactions: "Транзакции",
    type: "Тип",
    party: "Контрагент",
    productionDesc: "Активные производственные партии.",
    batch: "Партия",
    quantity: "Кол-во",
    start: "Начало",
    due: "Срок",
    liveMapDesc: "Отслеживание агентов в реальном времени.",
    activeAgents: "Активные агенты",
    reportsDesc: "Аналитические отчёты и показатели.",
    calendarDesc: "Запланированные события и задачи.",
    notificationsDesc: "Системные уведомления и оповещения.",
    settingsDesc: "Настройки рабочего пространства.",
    profileDesc: "Информация вашего профиля.",
    language: "Язык",
    theme: "Тема",
    light: "Светлая",
    dark: "Тёмная",
    notFound: "Ничего не найдено.",
    today: "Сегодня",
    growth: "рост",
    new: "новых",
    markRead: "Отметить прочитанным",
    upcoming: "Предстоящие события",
    noEvents: "На этот день событий нет.",
    online: "Онлайн",
    offline: "Офлайн",
    supervisor: "Супервайзер",
    deliverer: "Доставщик",
    allRoles: "Все",
    agents: "Агенты",
    supervisors: "Супервайзеры",
    deliverers: "Доставщики",
    speed: "Скорость",
    workStartTime: "Начало работы",
    distanceTraveled: "Пройдено",
    kmh: "км/ч",
    km: "км",
    agentInfo: "Информация агента",
    notAvailable: "Недоступно",
    clientsOnMap: "Клиенты на карте",
    showClients: "Показать клиентов",
    hideClients: "Скрыть клиентов",
    lastSale: "Последняя продажа",
    debt: "Долг",
    agent: "Агент",
    filial: "Филиал",
    noClients: "Клиенты не найдены",
    errorTitle: "Ошибка подключения",
    errorClientsLoad: "Не удалось загрузить список клиентов. Пожалуйста, попробуйте позже.",
  },
  en: {
    appTagline: "One platform to run your entire distribution business",
    welcomeBack: "Welcome back",
    signInSubtitle: "Sign in to your Distr workspace",
    email: "Email",
    password: "Password",
    signIn: "Sign in",
    demoNote: "Demo mode — any credentials work.",
    search: "Search…",
    logout: "Logout",
    dashboard: "Dashboard",
    clients: "Clients",
    sales: "Sales",
    staff: "Staff",
    warehouse: "Warehouse",
    finance: "Finance",
    production: "Production",
    liveMap: "Live Map",
    reports: "Reports",
    calendar: "Calendar",
    notifications: "Notifications",
    settings: "Settings",
    profile: "Profile",
    overview: "Overview of your business.",
    totalSales: "Total Sales",
    activeClients: "Active Clients",
    revenue: "Revenue",
    orders: "Orders",
    salesPerformance: "Sales performance",
    ordersByMonth: "Orders by month",
    recentActivity: "Recent activity",
    topClients: "Top clients",
    topStaff: "Top staff",
    salesByCategory: "By category",
    add: "Add",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    name: "Name",
    phone: "Phone",
    location: "Location",
    status: "Status",
    joined: "Joined",
    all: "All",
    active: "Active",
    inactive: "Inactive",
    pending: "Pending",
    delivered: "Delivered",
    cancelled: "Cancelled",
    inProgress: "In progress",
    completed: "Completed",
    delayed: "Delayed",
    clientsDesc: "Manage your customers and accounts.",
    addClient: "Add client",
    editClient: "Edit client",
    salesDesc: "Track orders and monthly performance.",
    monthlySales: "Monthly sales",
    orderId: "Order ID",
    client: "Client",
    date: "Date",
    amount: "Amount",
    staffDesc: "Team members, roles and performance.",
    role: "Role",
    performance: "Performance",
    warehouseDesc: "Warehouse products and inventory.",
    sku: "SKU",
    product: "Product",
    category: "Category",
    stock: "Stock",
    threshold: "Threshold",
    lowStock: "Low stock",
    inStock: "In stock",
    financeDesc: "Income, expenses and monthly summary.",
    income: "Income",
    expense: "Expense",
    netProfit: "Net profit",
    monthlySummary: "Monthly summary",
    transactions: "Transactions",
    type: "Type",
    party: "Party",
    productionDesc: "Active production batches.",
    batch: "Batch",
    quantity: "Quantity",
    start: "Start",
    due: "Due",
    liveMapDesc: "Real-time tracking of field agents.",
    activeAgents: "Active agents",
    reportsDesc: "Analytics reports and KPIs.",
    calendarDesc: "Scheduled events and tasks.",
    notificationsDesc: "System notifications and alerts.",
    settingsDesc: "Workspace settings.",
    profileDesc: "Your profile information.",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    notFound: "No results found.",
    today: "Today",
    growth: "growth",
    new: "new",
    markRead: "Mark as read",
    upcoming: "Upcoming events",
    noEvents: "No events for this day.",
    online: "Online",
    offline: "Offline",
    supervisor: "Supervisor",
    deliverer: "Deliverer",
    allRoles: "All",
    agents: "Agents",
    supervisors: "Supervisors",
    deliverers: "Deliverers",
    speed: "Speed",
    workStartTime: "Work start time",
    distanceTraveled: "Distance traveled",
    kmh: "km/h",
    km: "km",
    agentInfo: "Agent info",
    notAvailable: "Not available",
    clientsOnMap: "Clients on map",
    showClients: "Show clients",
    hideClients: "Hide clients",
    lastSale: "Last sale",
    debt: "Debt",
    agent: "Agent",
    filial: "Branch",
    noClients: "No clients found",
    errorTitle: "Connection error",
    errorClientsLoad: "Failed to load clients list. Please try again later.",
  },
} as const;

type Key = keyof (typeof dict)["uz"];

type Ctx = {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (k: Key) => string;
  theme: "light" | "dark";
  setTheme: (t: "light" | "dark") => void;
};

const C = createContext<Ctx | null>(null);

export function AppSettingsProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("uz");
  const [theme, setThemeState] = useState<"light" | "dark">("light");

  useEffect(() => {
    if (typeof window === "undefined") return;
    const l = (localStorage.getItem("distr.lang") as Lang) || "uz";
    const th = (localStorage.getItem("distr.theme") as "light" | "dark") || "light";
    setLangState(l);
    setThemeState(th);
  }, []);

  useEffect(() => {
    if (typeof document === "undefined") return;
    document.documentElement.classList.toggle("dark", theme === "dark");
  }, [theme]);

  const setLang = (l: Lang) => {
    localStorage.setItem("distr.lang", l);
    setLangState(l);
  };
  const setTheme = (t: "light" | "dark") => {
    localStorage.setItem("distr.theme", t);
    setThemeState(t);
  };

  const t = (k: Key) => dict[lang][k] ?? dict.en[k] ?? k;

  return <C.Provider value={{ lang, setLang, t, theme, setTheme }}>{children}</C.Provider>;
}

export function useSettings() {
  const ctx = useContext(C);
  if (!ctx) throw new Error("useSettings must be used within AppSettingsProvider");
  return ctx;
}

export const LANGS: { code: Lang; label: string; flag: string }[] = [
  { code: "uz", label: "O'zbekcha", flag: "🇺🇿" },
  { code: "ru", label: "Русский", flag: "🇷🇺" },
  { code: "en", label: "English", flag: "🇬🇧" },
];
