[build]
  command = "npm run build"
  publish = "dist/client"

[functions]
  directory = ".netlify/v1/functions"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
