[build]
  command = "npm run build"
  publish = "dist/client"
  functions = "netlify/functions"

[functions."ssr-serve"]
  node_bundler = "none"
  included_files = ["dist/server/**"]

[build.environment]
  NODE_VERSION = "20"
